### ISSUE TITLE
Job isn't marked as 'Completed'

### ISSUE THREAD

**Issue by izhilenkov** [keylimetoolbox/resque-kubernetes#15]
After a resque job is completed in kubernetes job it isn't marked as completed job
My manifest is like:
```
  def self.job_manifest
    YAML.safe_load(
        <<~MANIFEST
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: resque-job
      spec:
        template:
          metadata:
            name: resque-job
          spec:
            containers:
            - name: resque-job
              image: image
              command: ["bundle", "exec", "rake", "environment", "resque:work"]
              volumeMounts:
                - name: google-cloud-credentials
                  mountPath: /configs
                  readOnly: true
              env:
                - name: RAILS_ENV
                  value: #{ENV['RAILS_ENV']}
                - name: RACK_ENV
                  value: #{ENV['RAILS_ENV']}
                - name: REDIS_URL
                  value: "redis_url"
                - name: DB_POOL
                  value: "50"
                - name: QUEUE
                  value: "queue_name"
              resources:
                requests:
                  cpu: "200m"
                  memory: "1024Mi"
                limits:
                  cpu: "500m"
                  memory: "2048Mi"
    MANIFEST
    )
end
```
version 0.6.0
